// Подпись сессии в пикере. Замер по 233 сессиям agentek-console: у 5% первый промпт лежит
// глубже 64 КБ (прежнее окно чтения) — кнопка оставалась без текста; а половина телеграмных
// сессий начинается с «привет», и пять сессий подряд выглядели одинаково.
import { describe, expect, test, beforeEach } from 'bun:test'
import { mkdirSync, mkdtempSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { claudeProjectDir, pickUserSnippet, recentSessions } from '../src/session-id'

const PROJECT = '/home/user/projects/demo'
const user = (text: string) => JSON.stringify({ type: 'user', message: { content: text } })

describe('pickUserSnippet', () => {
  test('короткое приветствие уступает содержательному промпту', () => {
    const got = pickUserSnippet([user('привет'), user('Почини сборку фронта, она падает на типах')])
    expect(got.meaningful).toBe('Почини сборку фронта, она падает на типах')
    expect(got.first).toBe('привет')
  })

  test('служебные врезки на подпись не идут', () => {
    const lines = [
      user('Caveat: The messages below were generated by the user while running local commands'),
      user('This session is being continued from a previous conversation that ran out of context'),
      user('Разберись, почему воркер памяти молчит вторые сутки'),
    ]
    expect(pickUserSnippet(lines).meaningful).toBe('Разберись, почему воркер памяти молчит вторые сутки')
  })

  test('теги канала вырезаются, остаётся текст человека', () => {
    const line = user('<channel source="telegram" chat_id="-100" topic_id="7">\nСделай выгрузку по продажам за август\n</channel>')
    expect(pickUserSnippet([line]).meaningful).toBe('Сделай выгрузку по продажам за август')
  })

  test('результаты тулов и обрывки строк не путаются с промптом', () => {
    const toolResult = JSON.stringify({ type: 'user', message: { content: [{ type: 'tool_result', text: 'ok' }] } })
    const got = pickUserSnippet([toolResult, '{"type":"user","message":{"con', user('Собери релиз и выложи его в стейджинг')])
    expect(got.meaningful).toBe('Собери релиз и выложи его в стейджинг')
  })

  test('нет ничего содержательного — отдаём хотя бы первое', () => {
    expect(pickUserSnippet([user('ок'), user('да')])).toEqual({ first: 'ок' })
  })

  test('пустая сессия — пусто, а не выдумка', () => {
    expect(pickUserSnippet([JSON.stringify({ type: 'last-prompt', sessionId: 'x' })])).toEqual({})
  })
})

describe('recentSessions читает голову файла кусками', () => {
  let dir: string
  beforeEach(() => {
    process.env.HOME = mkdtempSync(join(tmpdir(), 'snippet-home-'))
    dir = claudeProjectDir(PROJECT)
    mkdirSync(dir, { recursive: true })
  })

  test('промпт за пределами прежнего окна в 64 КБ всё равно находится', () => {
    // блок вложений (CLAUDE.md, хуки) отжимает первый промпт вглубь — так лежит каждая 20-я сессия
    const filler = Array.from({ length: 400 }, (_, i) =>
      JSON.stringify({ type: 'attachment', i, blob: 'x'.repeat(500) }))
    const lines = [...filler, user('Перенеси сессию топика в другой проект вместе с памятью')]
    writeFileSync(join(dir, 'deep.jsonl'), lines.join('\n') + '\n')
    expect(Buffer.byteLength(lines.slice(0, -1).join('\n'))).toBeGreaterThan(64 * 1024)
    expect(recentSessions(PROJECT)[0]!.snippet).toBe('Перенеси сессию топика в другой проект вместе с памятью')
  })

  test('кириллица на границе куска не бьётся в кракозябры', () => {
    // граница чтения (256 КБ) режет многобайтный символ — декодер обязан склеить его обратно
    const pad = JSON.stringify({ type: 'attachment', blob: 'я'.repeat(140_000) })
    const lines = [pad, user('Проверь, что подпись не превратилась в вопросительные знаки')]
    writeFileSync(join(dir, 'utf.jsonl'), lines.join('\n') + '\n')
    expect(recentSessions(PROJECT)[0]!.snippet).toBe('Проверь, что подпись не превратилась в вопросительные знаки')
  })

  test('пустой файл не роняет список', () => {
    writeFileSync(join(dir, 'empty.jsonl'), '')
    expect(recentSessions(PROJECT)[0]).toMatchObject({ id: 'empty', snippet: '' })
  })
})
